---
- hosts: nodes
  become: true

  tasks:
    - name: Install Nginx 
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Remove Nginx 
      apt:
        name: nginx
        state: absent
