# ---
# - hosts: nodes
#   become: true

#   tasks:
#     - name: Install Nginx 
#       apt:
#         name: nginx
#         state: present
#         update_cache: yes

#     - name: Remove Nginx 
#       apt:
#         name: nginx
#         state: absent
---
- name: "Uninstall apache server"
  hosts: all
  become: true
  tasks:
    - name: "Uninstall packages"
      apt:
        name: nginx
        state: absent
    - name: "Stop nginx"
      service:
        name: nginx
        state: stopped
        enabled: no