---
- hosts: nodes
  become: true

  tasks:
    # - name: Install Nginx (for Debian-based systems)
    #   apt:
    #     name: nginx
    #     state: present
    #     update_cache: yes

    - name: Remove Nginx (for Debian-based systems)
      apt:
        name: nginx
        state: absent
