---
- hosts: nodes
  become: true

  tasks:
    - name: Stop Nginx service
      systemd:
        name: nginx
        state: stopped
      ignore_errors: yes

    - name: Disable Nginx service at boot
      systemd:
        name: nginx
        enabled: no

    - name: Remove Nginx package
      apt:
        name: nginx
        state: absent
      ignore_errors: yes

    - name: Purge Nginx configuration files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/nginx
        - /var/log/nginx
